=== LMatteo/IslandXml/island.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE championship [
	<!ELEMENT championship (initialization,(request,answer)*)>
		<!ELEMENT initialization (data,time,meth)>
		<!ELEMENT request ((data,time))>
		<!ELEMENT answer ((data,time))>
		<!ATTLIST request step CDATA>
		<!ATTLIST answer step CDATA>
		<!ELEMENT data (cost,extras,status)>
		<!ELEMENT cost (#PCDATA)>
		<!ELEMENT status (#PCDATA)>
		<!ELEMENT extras ((action|(heading,men,contracts,budget)|(action,parameters)|(range,found)|(biomes,creeks,sites)|(altitude,resources)|(report)|(exlorations,pois)|(production,kind))?)>
		<!ELEMENT action (#PCDATA)>
		<!ELEMENT time (#PCDATA)>
		<!ELEMENT meth (#PCDATA)>
		<!ELEMENT heading (#PCDATA)>
		<!ELEMENT men (#PCDATA)>
		<!ELEMENT contracts (contract)+>
		<!ELEMENT contract (amount,resource)>
		<!ELEMENT budget (#PCDATA)>
		<!ELEMENT parameters ((direction,range)|(creek,people)|(unit)+)>
		<!ELEMENT direction (#PCDATA)>
		<!ELEMENT range (#PCDATA)>
		<!ELEMENT creek (#PCDATA)>
		<!ELEMENT people (#PCDATA)>
		<!ELEMENT unit (resource,quantity)>
		<!ELEMENT resource (#PCDATA)>
		<!ELEMENT quantity (#PCDATA)>
		<!ELEMENT range (#PCDATA)>
		<!ELEMENT found (#PCDATA)>
		<!ELEMENT biomes (biome)*>
		<!ELEMENT biome (#PCDATA)>
		<!ELEMENT creeks (creek)*>
		<!ELEMENT sites (site)*>
		<!ELEMENT site (#PCDATA)>
		<!ELEMENT altitude (#PCDATA)>
		<!ELEMENT resources (resource)*>
		<!ELEMENT asked_range (#PCDATA)>
		<!ELEMENT report (tile)*>
		<!ELEMENT tile ((resource,percentage)|resource)*>
		<!ELEMENT percentage (#PCDATA)>
		<!ELEMENT exlorations (amount,resource,cond)>
		<!ELEMENT amount (#PCDATA)>
		<!ELEMENT resource (#PCDATA)>
		<!ELEMENT cond (#PCDATA)>
		<!ELEMENT pois (zone)*>
		<!ELEMENT zone (kind,id)>
		<!ELEMENT kind (#PCDATA)>
		<!ELEMENT id (#PCDATA)>
		<!ELEMENT production (#PCDATA)>

]>

=== LMatteo/IslandXml/island.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="style2.css" type="text/css" ?>
<!DOCTYPE championship SYSTEM "island.dtd">

<championship>

	<initialization>
		<data>
			<heading>S</heading>
			<men>10</men>
			<contracts>
				<contract>
					<amount>400</amount>
					<resource>RUM</resource>
				</contract>
				<contract>
					<amount>2000</amount>
					<resource>WOOD</resource>
				</contract>
			</contracts>
			<budget>30000</budget>
		</data>
		<part>Engine</part>
		<time>16815132</time>
	</initialization>

	<!--  REQUEST -->

	<element>
		<data>
			<action>fly</action>
		</data>
		<part>Engine</part>
		<time>16815132</time>
	</element>

	<element>
		<data>
			<action>heading</action>
			<parameters>
				<direction>N</direction>
				<range>2</range>
			</parameters>
		</data>
		<part>Explorer</part>
		<time>16815132</time>
		<meth>takeDecision</meth>
	</element>

	<element>
		<data>
			<action>land</action>
			<parameters>
				<creek>id</creek>
				<people>42</people>
			</parameters>
		</data>
		<part>Engine</part>
		<time>16815132</time>
		<meth>takeDecision</meth>
	</element>

	<element>
		<data>
			<action>transform</action>
			<parameters>
				<unit>
					<resource>WOOD</resource>
					<quantity>6</quantity>
				</unit>
				<unit>
					<resource>QUARTZ</resource>
					<quantity>11</quantity>
				</unit>
			</parameters>
		</data>
		<part>Engine</part>
		<time>16815132</time>
		<meth>takeDecision</meth>
	</element>


	<!--  ANSWERS -->

	<element>
		<data>
			<cost>2</cost>
			<extras>
				<range>2</range>
				<found>GROUND</found>
			</extras>
			<status>OK</status>
		</data>
		<part>Engine</part>
		<time>16815132</time>
	</element>

	<element>
		<data>
			<cost>2</cost>
			<extras>
				<biomes>
					<biome>GLACIER</biome>
					<biome>ALPINE</biome>
					<creeks>
						<creek>id</creek>
					</creeks>
					<sites>
						<site>toto</site>
					</sites>
				</biomes>
			</extras>
			<status>OK</status>
		</data>
		<part>Engine</part>
		<time>16815132</time>
	</element>

	<element>
		<data>
			<cost>2</cost>
			<extras>
				<altitude>1</altitude>
				<resources>
					<resource>FUR</resource>
					<resource>WOOD</resource>
				</resources>
			</extras>
			<status>OK</status>
		</data>
		<part>Engine</part>
		<time>16815132</time>
	</element>

	<element>
		<data>
			<cost>3</cost>
			<extras>
				<asked_range>4</asked_range>
				<report>
					<tile>
						<resource>BEACH</resource>
						<percentage>59.35</percentage>
					</tile>
					<tile>
						<resource>OCEAN</resource>
					</tile>
				</report>
			</extras>
			<status>OK</status>
		</data>
		<part>Engine</part>
		<time>16815132</time>
	</element>

	<element>
		<data>
			<cost>5</cost>
			<extras>
				<resources>
					<explorations>
						<exploration>
							<amount>HIGH</amount>
							<resource>FUR</resource>
							<cond>FAIR</cond>
						</exploration>
					</explorations>
				</resources>
				<pois>
					<zone>
						<kind>Creek</kind>
						<id>43e3eb42-50f0-47c5-afa3-16cd3d50faff</id>
					</zone>
				</pois>
			</extras>
			<status>OK</status>
		</data>
		<part>Engine</part>
		<time>16815132</time>
	</element>

	<element>
		<data>
			<cost>5</cost>
			<extras>
				<production>1</production>
				<kind>GLASS</kind>
			</extras>
			<status>OK</status>
		</data>
		<part>Engine</part>
		<time>16815132</time>
	</element>

</championship>
